### ISSUE TITLE
Editing Patient's name is causing Demo app to crash.

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#1029]
**Describe the bug**
Editing Patient's name is causing Demo app to crash because ResourceMapper throws exception while extracting the Patient resource.

```
2022-01-12 21:07:54.364 9407-9407/com.google.android.fhir.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.demo, PID: 9407
    java.lang.ClassCastException: org.hl7.fhir.r4.model.HumanName cannot be cast to org.hl7.fhir.r4.model.Resource
        at com.google.android.fhir.datacapture.mapping.ResourceMapperKt.createResource(ResourceMapper.kt:573)
        at com.google.android.fhir.datacapture.mapping.ResourceMapperKt.access$createResource(ResourceMapper.kt:1)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractResourceByDefinition(ResourceMapper.kt:340)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractByDefinition(ResourceMapper.kt:289)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractByDefinition(ResourceMapper.kt:252)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractByDefinition(ResourceMapper.kt:308)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractByDefinition(ResourceMapper.kt:252)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractByDefinition(ResourceMapper.kt:119)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extract(ResourceMapper.kt:101)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extract$default(ResourceMapper.kt:94)
        at com.google.android.fhir.demo.EditPatientViewModel$updatePatient$1.invokeSuspend(EditPatientViewModel.kt:75)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.google.android.fhir.demo.EditPatientViewModel.updatePatient(EditPatientViewModel.kt:73)
        at com.google.android.fhir.demo.EditPatientFragment.onSubmitAction(EditPatientFragment.kt:95)
        at com.google.android.fhir.demo.EditPatientFragment.onOptionsItemSelected(EditPatientFragment.kt:73)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3111)
        at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3222)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3115)
        at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3222)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:416)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:358)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
2022-01-12 21:07:54.364 9407-9407/com.google.android.fhir.demo E/AndroidRuntime:     at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
```

**Component**
Core library, Demo

**To Reproduce**
1. Edit Patient name by going to Patient details page and hitting edit icon on top right.
2. Change first name or last name.
3. Save.

**Expected behavior**
Patient should get saved.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by aditya-07** [comment]
Adding a new Patient in demo app causes the same issue as well.

**Comment by Itskiprotich** [comment]
Also when Submitting a questionaire same problem
