### ISSUE TITLE
Passing a different subject other than test patient (Charity Otala) causes the measure reporting for Individual to crash  on the $evaluate_meaasure API for  Individual subject MeasureReport generation

### ISSUE THREAD

**Issue by f-odhiambo** [google/android-fhir#1071]
**Describe the bug**
Passing a different subject other than test patient (Charity Otala) causes the measure reporting for Individual to crash  on the $evaluate_meaasure API for  Individual subject MeasureReport generation

**Component**
Measure Reporting via $evaluate _module

**To Reproduce**
1. Go to Test Class
2. Swap the patient ID charity-otala-1 to another Patient ID

```
fun evaluateMeasure() = runBlocking {
  val measureReport =
    fhirOperator.evaluateMeasure(
      "http://fhir.org/guides/who/anc-cds/Measure/ANCIND01",
      "2020-01-01",
      "2020-01-31",
      "subject",
      "charity-otala-1"
    )

```
**Expected behavior**
Return  an appropriate  measure report for given subject

**Screenshots**
Sharing FHIR Core Screenshots

**Smartphone (please complete the following information):**
 - Device: [ Pixel4a emulator ]
 - Version [e.g. 32]

**Additional context**

CQL Version  - org.opencds.cqf.cql:engine:1.3.1-SNAPSHOT

Logcat 
```
2022-01-13 18:00:20.436 1761-2221/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2022-01-13 18:00:20.436 1761-2221/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2022-01-13 18:00:20.605 13304-13403/org.smartregister.fhircore.anc V/TokenManagerService: Checking local storage for access token
2022-01-13 18:00:20.611 13304-13390/org.smartregister.fhircore.anc I/MeasureEvaluation: Could not determine subjectType. Defaulting to Patient
2022-01-13 18:00:20.613 13304-13390/org.smartregister.fhircore.anc I/MeasureEvaluation: Evaluating Measure http://fhir.org/guides/who/anc-cds/Measure/ANCIND01, report type individual, with 1 subject(s)
    
    --------- beginning of crash
2022-01-13 18:00:20.617 13304-13304/org.smartregister.fhircore.anc E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.anc, PID: 13304
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at org.opencds.cqf.cql.evaluator.measure.common.MeasureEvaluation.setContextToSubject(MeasureEvaluation.java:261)
        at org.opencds.cqf.cql.evaluator.measure.common.MeasureEvaluation.evaluateGroup(MeasureEvaluation.java:456)
        at org.opencds.cqf.cql.evaluator.measure.common.MeasureEvaluation.innerEvaluate(MeasureEvaluation.java:299)
        at org.opencds.cqf.cql.evaluator.measure.common.MeasureEvaluation.evaluate(MeasureEvaluation.java:283)
        at org.opencds.cqf.cql.evaluator.measure.common.MeasureEvaluation.evaluate(MeasureEvaluation.java:107)
        at org.opencds.cqf.cql.evaluator.measure.r4.R4MeasureProcessor.evaluateMeasure(R4MeasureProcessor.java:203)
        at com.google.android.fhir.workflow.FhirOperator.evaluateMeasure(FhirOperator.kt:67)
        at org.smartregister.fhircore.anc.ui.report.ReportHomeActivity$onCreate$4$1$1.invokeSuspend(ReportHomeActivity.kt:141)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-01-13 18:00:20.619 1995-4625/? W/ActivityTaskManager:   Force finishing activity org.smartregister.fhircore.anc/.ui.report.ReportHomeActivity
2022-01-13 18:00:20.619 1995-4625/? W/InputReader: Device has associated, but no associated display id.
2022-01-13 18:00:20.624 1995-13417/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2022-01-13 18:00:20.619 1995-4625/? I/chatty: uid=1000(system) Binder:1995_15 identical 8 lines
2022-01-13 18:00:20.619 1995-4625/? W/InputReader: Device has associated, but no associated display id.
2022-01-13 18:00:20.624 13304-13304/org.smartregister.fhircore.anc I/Process: Sending signal. PID: 13
```

**Would you like to work on the issue?**
N/A

**Comment by jingtang10** [comment]
@f-odhiambo, thanks for raising this! The test loads specific artifacts such as the patient resource: https://github.com/google/android-fhir/blob/da168b420dba8fa12b357997834f968c38da5fa3/workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt#L55

so changing the patient to another id would make the test fail - have you tried to load another patient in fhir engine?

**Comment by f-odhiambo** [comment]
@jingtang10 As mentioned in the Evaluation check in call , we were able to troubleshoot and add measure reporting for Individual and Population Measure Reporting . Will push my changes. I think will need some support from JP and Brynn to get test sample data, so testing  this is kinda blocked  

CC @ellykits

**Comment by f-odhiambo** [comment]
Tested this and works well with the current PR #1091. Open issue on testing https://github.com/google/android-fhir/issues/1107
