### ISSUE TITLE
Timing type with missing event field crashes application in ResourceIndexer with NPE.

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#1282]
**Describe the bug**

`Timing` (http://hl7.org/fhir/datatypes.html#Timing) type with missing `event` crashes application in ResourceIndexer with NPE.

```
2022-04-06 15:38:07.496 9331-9331/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 9331
    java.util.NoSuchElementException
        at com.google.android.fhir.index.ResourceIndexer.dateTimeIndex(ResourceIndexer.kt:190)
        at com.google.android.fhir.index.ResourceIndexer.extractIndexValues(ResourceIndexer.kt:84)
        at com.google.android.fhir.index.ResourceIndexer.index(ResourceIndexer.kt:68)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertResource(ResourceDao.kt:202)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll$suspendImpl(ResourceDao.kt:74)
```

**Component**
Core library

**To Reproduce**
1. Add a CarePlan with Timing field and no 'event' and save into DB 
```
{
	"resourceType": "CarePlan",
	"status": "active",
	"intent": "plan",
	"title": "Child Routine visit CarePlan",
	"description": "This defines the schedule of care for patients under 5 years old",
	"subject": {
	    "reference": "Patient/36eb5dae-cdff-4049-9dce-470fe286cc9e"
	},
	"period": {
	    "start": "2022-04-06T00:00:00",
	    "end": "2026-12-01T00:00:00"
	},
	"created": "2022-04-06T13:55:50+00:00",
	"activity": [
	    {
		"detail": {
		    "kind": "Task",
		    "code": {
		        "coding": [
		            {
		                "system": "http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation",
		                "code": "MO",
		                "display": "MO"
		            }
		        ],
		        "text": "MO"
		    },
		    "status": "in-progress",
		    "scheduledTiming": {
		        "repeat": {
		            "count": 55,
		            "countMax": 60,
		            "duration": 2,
		            "durationMax": 4,
		            "durationUnit": "h",
		            "frequency": 1,
		            "frequencyMax": 1,
		            "period": 1,
		            "periodMax": 1,
		            "periodUnit": "mo"
		        }
		    },
		    "description": "Child Monthly Routine visit"
		}
	    }
	]
}
```
2- Right after save when indexing it would crash and would save if any value is added to timing.event. 
ResourceIndexer L#185 should not use max and assumes a non null/empty event field
```
"Timing" -> {
        val timing = value as Timing
        DateTimeIndex(
          searchParam.name,
          searchParam.path,
          timing.event.minOf { it.value.time },
          timing.event.maxOf { it.precision.add(it.value, 1).time } - 1
        )
      }
```

**Expected behavior**
It should not crash as event is nullable by spec http://hl7.org/fhir/datatypes.html#Timing.

**Comment by jingtang10** [comment]
I think it would be quite a lot harder to handle the repeat cases in the timing object...

in this pr we probably should focus on the case without repeat.

and we should probably raise another issue to handle repeat (low priority).
