### ISSUE TITLE
  App crash on  text input for age on Calculated expression screen

### ISSUE THREAD

**Issue by PallaviGanorkar** [google/android-fhir#1667]
**Describe the bug**

**Component**
SDC library,  SDC gallery app

**To Reproduce**
1. Go to 'Behavior -> calculated expression in Catalog app.'
2. Enter text text in Age input box
3. See error : app crash with java.lang.NumberFormatException

**Expected behavior**
App should not crash

**Screenshots**
logs are are pasted below

**Smartphone (please complete the following information):**
 - Device: all devices
 

**Additional context**

**Would you like to work on the issue?**
Yes

**Comment by PallaviGanorkar** [comment]
2022-10-15 07:42:33.485 32704-32704/com.google.android.fhir.catalog E/InputEventSender: Exception dispatching finished signal for seq=8
2022-10-15 07:42:33.485 32704-32704/com.google.android.fhir.catalog E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2022-10-15 07:42:33.490 32704-32704/com.google.android.fhir.catalog E/MessageQueue-JNI: java.lang.NumberFormatException
        at java.math.BigDecimal.<init>(BigDecimal.java:497)
        at java.math.BigDecimal.<init>(BigDecimal.java:383)
        at java.math.BigDecimal.<init>(BigDecimal.java:809)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextQuantityViewHolderFactory$getQuestionnaireItemViewHolderDelegate$1.getValue(QuestionnaireItemEditTextQuantityViewHolderFactory.kt:43)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextViewHolderDelegate.updateAnswer(QuestionnaireItemEditTextViewHolderFactory.kt:96)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextViewHolderDelegate.access$updateAnswer(QuestionnaireItemEditTextViewHolderFactory.kt:45)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextViewHolderDelegate$bind$$inlined$doAfterTextChanged$1.afterTextChanged(TextView.kt:98)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10805)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13820)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1278)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
        at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:228)
        at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
        at android.widget.TextView.doKeyDown(TextView.java:8557)
        at android.widget.TextView.onKeyDown(TextView.java:8331)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2854)
        at android.view.View.dispatchKeyEvent(View.java:14537)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:490)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1880)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4159)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:404)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6377)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6243)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5725)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
2022-10-15 07:42:33.490 32704-32704/com.google.android.fhir.catalog E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5913)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5756)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5970)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5729)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5756)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5729)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5946)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6104)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3159)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2723)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2714)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3136)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-10-15 07:42:33.493 32704-32704/com.google.android.fhir.catalog E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.catalog, PID: 32704
    java.lang.NumberFormatException
        at java.math.BigDecimal.<init>(BigDecimal.java:497)
        at java.math.BigDecimal.<init>(BigDecimal.java:383)
        at java.math.BigDecimal.<init>(BigDecimal.java:809)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextQuantityViewHolderFactory$getQuestionnaireItemViewHolderDelegate$1.getValue(QuestionnaireItemEditTextQuantityViewHolderFactory.kt:43)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextViewHolderDelegate.updateAnswer(QuestionnaireItemEditTextViewHolderFactory.kt:96)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextViewHolderDelegate.access$updateAnswer(QuestionnaireItemEditTextViewHolderFactory.kt:45)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextViewHolderDelegate$bind$$inlined$doAfterTextChanged$1.afterTextChanged(TextView.kt:98)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10805)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13820)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1278)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
        at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:228)
        at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
        at android.widget.TextView.doKeyDown(TextView.java:8557)
        at android.widget.TextView.onKeyDown(TextView.java:8331)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2854)
        at android.view.View.dispatchKeyEvent(View.java:14537)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1964)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:490)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1880)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4159)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:404)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6377)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6243)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5725)
2022-10-15 07:42:33.494 32704-32704/com.google.android.fhir.catalog E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5913)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5756)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5970)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5729)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5756)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5729)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5946)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6104)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3159)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2723)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2714)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3136)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by jingtang10** [comment]
i don't think we need to go out of our way to accept `.5` or `1,000`. this is because these ways of input are highly locale dependent and i worry that if we get into the business of trying to fix the format or second guess the intended value we'll end up doing the job of the icu library.

so, if we can find a library that accepts these values, it would be nice. but if not, we should fix the crash and make sure we display an error message to tell the user the input is invalid.

**Comment by PallaviGanorkar** [comment]
@shelaghm  Could you please provide error message to displayin case the user has entered value starts with dot(.) eg .5 or comma(,) in between.

**Comment by shelaghm** [comment]
@PallaviGanorkar  Maybe something like this:
No commas (,) or negative numbers (eg. -1) allowed. 
Period (.) can only be used after a number (eg. 1.5, but not .5)

I know it is long, but I think because it is so specific we need to explain it thoroughly.
