### ISSUE TITLE
Invalid JSON element for number: "8"

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#174]
To reproduce:

Click Patient registration example.

Error:

2021-01-24 14:26:56.251 13762-13762/com.google.android.fhir.datacapture.gallery E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.datacapture.gallery, PID: 13762
    java.lang.RuntimeException: An exception happened in constructor of class com.google.android.fhir.datacapture.QuestionnaireViewModel
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:132)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.google.android.fhir.datacapture.QuestionnaireFragment.getViewModel(Unknown Source:2)
        at com.google.android.fhir.datacapture.QuestionnaireFragment.onViewCreated(QuestionnaireFragment.kt:53)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2974)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:538)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3122)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3056)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Error parsing field: google.fhir.r4.core.Extension.ValueX.integer
        at com.google.fhir.common.JsonFormat$Parser.parseFieldValue(JsonFormat.java:957)
        at com.google.fhir.common.JsonFormat$Parser.mergeField(JsonFormat.java:857)
        at com.google.fhir.common.JsonFormat$Parser.mergeChoiceField(JsonFormat.java:826)
        at com.google.fhir.common.JsonFormat$Parser.mergeMessage(JsonFormat.java:762)
        at com.google.fhir.common.JsonFormat$Parser.parseFieldValue(JsonFormat.java:971)
        at com.google.fhir.common.JsonFormat$Parser.mergeRepeatedField(JsonFormat.java:897)
        at com.google.fhir.common.JsonFormat$Parser.mergeField(JsonFormat.java:855)
        at com.google.fhir.common.JsonFormat$Parser.mergeMessage(JsonFormat.java:764)
        at com.google.fhir.common.JsonFormat$Parser.parseFieldValue(JsonFormat.java:971)
        at com.google.fhir.common.JsonFormat$Parser.mergeRepeatedField(JsonFormat.java:897)
        at com.google.fhir.common.JsonFormat$Parser.mergeField(JsonFormat.java:855)
        at com.google.fhir.common.JsonFormat$Parser.mergeMessage(JsonFormat.java:764)
        at com.google.fhir.common.JsonFormat$Parser.parseFieldValue(JsonFormat.java:971)
2021-01-24 14:26:56.251 13762-13762/com.google.android.fhir.datacapture.gallery E/AndroidRuntime:     at com.google.fhir.common.JsonFormat$Parser.mergeRepeatedField(JsonFormat.java:897)
        at com.google.fhir.common.JsonFormat$Parser.mergeField(JsonFormat.java:855)
        at com.google.fhir.common.JsonFormat$Parser.mergeMessage(JsonFormat.java:764)
        at com.google.fhir.common.JsonFormat$Parser.merge(JsonFormat.java:680)
        at com.google.fhir.common.JsonFormat$Parser.merge(JsonFormat.java:691)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel.<init>(QuestionnaireViewModel.kt:40)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:122)
        	... 31 more
     Caused by: java.lang.IllegalArgumentException: Invalid JSON element for number: "8"
        at com.google.fhir.wrappers.PrimitiveWrappers.checkIsNumber(PrimitiveWrappers.java:204)
        at com.google.fhir.wrappers.PrimitiveWrappers.parseAndWrap(PrimitiveWrappers.java:155)
        at com.google.fhir.common.JsonFormat$Parser.parseFieldValue(JsonFormat.java:953)
        	... 52 more

**Comment by jingtang10** [comment]
It seems that the problem is that the "valueInteger" fields in the patient registration questionnaire are string types.

It's working for me after I changed:

```
"valueInteger": "8"
```

to

```
"valueInteger": 8
```

in the patient-registration.json file (there're 6 occurences).

@fredhersch maybe this is a bug from the tool you used to generate the questionnaire -- maybe worth filing a bug to them?

Meanwhile I'll send a PR to fix this.

**Comment by jingtang10** [comment]
Hi @fredhersch -- can you please close this after verifying how the questionnaire was generated? thanks!

**Comment by jingtang10** [comment]
@fredhersch I checked the spec http://build.fhir.org/ig/HL7/sdc/behavior.html and I'm pretty sure that we shouldn't be using an extension for max length -- because it's actully a core element already defined on questionnaire item https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.maxLength

Additionally, judging by the min length extension (which *IS* an extension rather than defined on the core questionnaire resource), the way we handle the integer fields are correct.

So what's left to resolve before we close this issue, is to update the questionnaire to use the maxLength on questionnaire item and remove the maxlength extensions.
