### ISSUE TITLE
Questionnaire item using answer expression extension is crashing the app

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1798]
**Describe the bug**
When a questionnaire with an item that uses the answer expression extension is opened, the app immediately crashes

**Component**
SDC library

**To Reproduce**
Open a questionnaire with an item using the answer expression extension

**Expected behavior**
I expect the questionnaire to open and populate the item accordingly

**Screenshots**
N/A

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
This was working before when I was posted this [issue](https://github.com/google/android-fhir/issues/1735). Here is the [questionnaire](https://github.com/google/android-fhir/files/10382447/answer-expression-sample.txt) being used. The log is shown below:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.demo, PID: 10736
    java.lang.IllegalStateException: XFhirQueryResolver cannot be null. Please provide the XFhirQueryResolver via DataCaptureConfig.
        at com.google.android.fhir.datacapture.QuestionnaireViewModel.loadAnswerExpressionOptions(QuestionnaireViewModel.kt:456)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel.resolveAnswerExpression(QuestionnaireViewModel.kt:443)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel$getQuestionnaireAdapterItems$items$1$2.invokeSuspend(QuestionnaireViewModel.kt:602)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel$getQuestionnaireAdapterItems$items$1$2.invoke(Unknown Source:12)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel$getQuestionnaireAdapterItems$items$1$2.invoke(Unknown Source:10)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemViewItem$answerOption$1.invokeSuspend(QuestionnaireItemViewItem.kt:180)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by aditya-07** [comment]
@KhumboLihonga With PR #1742 , we have removed the direct dependency of SDC lib on fhir engine. So going forward, Developer app needs to provide a `XFhirQueryResolver` implementation in the DataCaptureConfig. The `XFhirQueryResolver` implementation may directly talk to fhir engine or other Fhir resource provider to resolve the XFhir-query.

**Comment by KhumboLihonga** [comment]
@aditya-07 thanks for letting me know. We will update accordingly.
