### ISSUE TITLE
Workflow: App crashes with NoSuchMethodError (getLogger) when calling FhirOperator

### ISSUE THREAD

**Issue by omarismail94** [google/android-fhir#1800]
**Describe the bug**

App crashed with the stack trace when initialising the `FhirOperator`:

```
 java.lang.NoSuchMethodError: No static method getLogger(Ljava/lang/String;)Ljava/lang/System$Logger; in class Ljava/lang/System; or its super classes (declaration of 'java.lang.System' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at com.github.benmanes.caffeine.cache.Caffeine.<clinit>(Caffeine.java:142)
                                                                                                    	at com.github.benmanes.caffeine.cache.Caffeine.newBuilder(Caffeine.java:254)
                                                                                                    	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.<init>(HapiWorkerContext.java:69)
                                                                                                    	at org.hl7.fhir.r4.hapi.fluentpath.FhirPathR4.<init>(FhirPathR4.java:23)
                                                                                                    	at org.hl7.fhir.r4.hapi.ctx.FhirR4.createFhirPathExecutor(FhirR4.java:47)
                                                                                                    	at ca.uhn.fhir.context.FhirContext.newFhirPath(FhirContext.java:822)
                                                                                                    	at org.opencds.cqf.cql.evaluator.fhir.util.FhirPathCache.lambda$cachedForContext$0(FhirPathCache.java:18)
                                                                                                    	at org.opencds.cqf.cql.evaluator.fhir.util.FhirPathCache$$ExternalSyntheticLambda0.apply(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710)
                                                                                                    	at org.opencds.cqf.cql.evaluator.fhir.util.FhirPathCache.cachedForContext(FhirPathCache.java:18)
                                                                                                    	at org.opencds.cqf.cql.evaluator.library.CqlFhirParametersConverter.<init>(CqlFhirParametersConverter.java:52)
                                                                                                    	at com.google.android.fhir.workflow.FhirOperator.<init>(FhirOperator.kt:86)
```

**Component**
Workflow Library

**To Reproduce**
Clone my repo:
```
https://github.com/omarismail94/android-fhir.git
```

Then checkout  the branch: `doesNotWorkFlow` :

```
git checkout doesNotWorkflow
```

Launch the demo app onto a connected device or emulator:
```
./gradlew :app:installDebug
```

The app I made is based on the Wiki guide: https://github.com/google/android-fhir/wiki/WFL%3A-Getting-Started

**Expected behavior**
I expect the app to load.  I set the minSDK version to 28, after looking at Issue #1627  but that did not help. 

**Smartphone (please complete the following information):**
 - Device: Pixel 7

**Comment by omarismail94** [comment]
@vitorpamplona  If you have a chance, can you look at this and let me know what I am missing? I feel Im missing something simple but I've been banging away at this for a couple of hours and can't find a solution

**Comment by omarismail94** [comment]
Thanks to @aditya-07 , I am able to resolve this issue. I have to add this block to my demo build file:


```
configurations {
  all {
    removeIncompatibleDependencies()
    forceHapiVersion()
  }
}
```

I see this block as well in the Workflow lib, why doesn't compiling the Workflow lib as a JAR include the dependencies that result from `forceHapiVersion`?
