### ISSUE TITLE
Exception in FHIR demo app while using latest local build of SDK

### ISSUE THREAD

**Issue by khyativyasargus** [google/android-fhir#1824]
**Describe the bug**
 On using latest local build: https://github.com/khyativyasargus/android-fhir/actions/runs/3967867003
 the demo app crashes on click add new patient button (bottom right plus icon). The only change done is syncing the latest 
 commit from master. 

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**
Clone the latest master branch code from [google repository](https://github.com/google/android-fhir) 

1. Go to Demo ->  **build.gradle.kts(demo)** file
2. Scroll down to line no. 64, comment following lines (module dependency of sdk)
  implementation(project(":datacapture")) {
    exclude(group = Dependencies.androidFhirGroup, module = Dependencies.androidFhirEngineModule)
  }
  implementation(project(":engine"))
  
  
  & add following lines ([local maven dependency](https://github.com/khyativyasargus/android-fhir/actions/runs/3967867003) forked 
  from latest FHIR library)
  
  implementation ("com.google.android.fhir:engine:0.1.0-beta02-build_3967867003")
  implementation ("com.google.android.fhir:data-capture:0.1.0-beta06-build_3967867003")
  implementation ("com.google.android.fhir:workflow:0.1.0-alpha02-build_3967867003")
  
3. login to your git-hub account and download maven-repository file from [local build](https://github.com/khyativyasargus/android-fhir/actions/runs/3967867003) , 
extract zip to download folder & add that path in project level gradle file **build.gradle.kts(andrid-fhir)** as following

allprojects {
  repositories {
    google()
    mavenCentral()
    maven(url = "https://oss.sonatype.org/content/repositories/snapshots")
    maven(url = "<MAVEN_REPOSITORY_DIRECTORY_PATH>") 
    gradlePluginPortal()
  }
  configureSpotless()
}

where replace MAVEN_REPOSITORY_DIRECTORY_PATH with maven directory path downloaded at your local ,
 \\ for example  maven(url = "file:///home/khyati/Downloads/maven-repository")

4. Go to buildSrc -> src -> main -> kotlin -> sdk.kt file and change minSdk version from 24 to 28 (as per latest library requirments)

5. Sync Gradle and Run the demo app

6. Wait for sync to finish and click on the (+) icon on bottom right (to open add patient questionnaire).
The app crashes immediately with 
 Caused by: java.lang.NoSuchMethodError: No static method getLogger(Ljava/lang/String;)Ljava/lang/System$Logger; in class Ljava/lang/System; or its super classes (declaration of 'java.lang.System' appears in /apex/com.android.art/javalib/core-oj.jar)
        at com.github.benmanes.caffeine.cache.Caffeine.<clinit>(Caffeine.java:142)
        at com.github.benmanes.caffeine.cache.Caffeine.newBuilder(Caffeine.java:254)
        at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.<init>(HapiWorkerContext.java:69)
             at com.google.android.fhir.datacapture.utilities.FhirPathUtilKt.<clinit>(FhirPathUtil.kt:27)
        at com.google.android.fhir.datacapture.utilities.FhirPathUtilKt.getFhirPathEngine(FhirPathUtil.kt:25)
        at com.google.android.fhir.datacapture.enablement.EnablementEvaluator.evaluate(EnablementEvaluator.kt:108)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel.getQuestionnaireAdapterItems(QuestionnaireViewModel.kt:582)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel.access$getQuestionnaireAdapterItems(QuestionnaireViewModel.kt:56)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel$getQuestionnaireAdapterItems$1.invoke(QuestionnaireViewModel.kt:565)
        at com.google.android.fhir.datacapture.QuestionnaireViewModel$getQuestionnaireAdapterItems$1.invoke(QuestionnaireViewModel.kt:554)

**Expected behavior**
Demo app should run smoothly with latest local build as it used to be. 
I am not sure what might be the reason behind this crash , I also tried to upgrade multiple dependencies but no help! 

**Smartphone (please complete the following information):**
 - Device: Pixel4 emulator API 31
 - Android version: 12

cc: @jingtang10

**Comment by omarismail94** [comment]
Please see https://github.com/google/android-fhir/issues/1800#issuecomment-1379400891 for solution as I had the same issue

**Comment by khyativyasargus** [comment]
Thanks a lot @omarismail94 It helped!

**Comment by omarismail94** [comment]
Great to hear that it worked! I will go ahead and close this Issue, but feel free to re-open if you feel it is not resolved
