### ISSUE TITLE
Missing Runtime FHIR model class types when using the Cached R4 context

### ISSUE THREAD

**Issue by ndegwamartin** [google/android-fhir#2007]
**Describe the bug**
There's as a strange issue that occurs when using the workflow library to generate reports using CQL
The classes `org.hl7.fhir.r4.model.BundleType` and `SearchParameter$SearchComparator` classes are not resolved by the [FHIR Model Resolver](https://github.com/cqframework/cql-engine/blob/master/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/model/FhirModelResolver.java)  because they are not present in the data structure here at run time. 

An exception is thrown in the line here [../model/FhirModelResolver.java#L295](https://github.com/cqframework/cql-engine/blob/69eaee563486b405710464c7b1be550df6b774fa/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/model/FhirModelResolver.java#L295)
 

**Component**
Workflow library

**To Reproduce**

**Expected behavior**
All HAPI FHIR structure models should be loaded in the **FhirModelResolver** class and [should not throw a missing class exception at runtime](https://github.com/cqframework/cql-engine/blob/69eaee563486b405710464c7b1be550df6b774fa/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/model/FhirModelResolver.java#L295)

**Screenshots**

Stacktrace

```java
org.opencds.cqf.cql.engine.fhir.exception.UnknownType: Could not resolve type BundleType. Primary package(s) for this resolver are org.hl7.fhir.r4.model
                                                                                        	at org.opencds.cqf.cql.engine.fhir.model.FhirModelResolver.resolveType(FhirModelResolver.java:295)
                                                                                        	at org.opencds.cqf.cql.engine.fhir.model.R4FhirModelResolver.resolveType(R4FhirModelResolver.java:189)
                                                                                        	at org.opencds.cqf.cql.evaluator.engine.model.CachingModelResolverDecorator.resolveType(CachingModelResolverDecorator.java:64)
                                                                                        	at org.opencds.cqf.cql.engine.data.CompositeDataProvider.resolveType(CompositeDataProvider.java:54)
                                                                                        	at org.opencds.cqf.cql.engine.execution.Context.resolveType(Context.java:457)
                                                                                        	at org.opencds.cqf.cql.engine.execution.Context.resolveType(Context.java:462)
                                                                                        	at org.opencds.cqf.cql.engine.execution.Context.resolveOperandType(Context.java:510)
                                                                                        	at org.opencds.cqf.cql.engine.execution.Context.resolveFunctionRef(Context.java:564)
                                                                                        	at org.opencds.cqf.cql.engine.execution.Context.resolveFunctionRef(Context.java:596)
                                                                                        	at org.opencds.cqf.cql.engine.elm.execution.FunctionRefEvaluator.internalEvaluate(FunctionRefEvaluator.java:23)
                                                                                        	at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:14)
                                                                                        	at org.opencds.cqf.cql.engine.elm.execution.FunctionRefEvaluator.internalEvaluate(FunctionRefEvaluator.java:17)
                                                                                        	at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:14)
                                                                                        	at org.opencds.cqf.cql.engine.elm.execution.ExpressionDefEvaluator.internalEvaluate(ExpressionDefEvaluator.java:23)
                                                                                        	at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:14)
```

**Smartphone (please complete the following information):**
 - Device: Pixel3XL emulator]
 - Android version: 12 
 - API Version 31
 - RAM 4GB, VM Heap 1 GB
 - Storage: Internal Storage 6GB, SD Card(Studio Managed) 4 GB
 <img width="382" alt="Screenshot 2023-05-18 at 13 28 38" src="https://github.com/google/android-fhir/assets/10017086/a0f3b672-6428-4102-9efd-381fee56823c">

**Additional context**
- Sometimes it works but sometime it doesn't, even on the same device
- There is no obvious pattern to the flakiness
- The current workaround is to swap the cached version with the non-cached version i.e. `FhirContext.forR4Cached()` vs `FhirContext.forR4()`.
- So far, we have only observed this when generating reports in the _Workflow_ library.
- So far, only the above two specified classes are missing/throw the exception i.e. _BundleType_ and  _SearchParameter$SearchComparator_

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by ndegwamartin** [comment]
Created the issue to track this cc @dubdabasoduba @f-odhiambo @roy @maimoonak  @jingtang10 @khyativyasargus

**Comment by aditya-07** [comment]
@ktarasenko @vitorpamplona FYI.
