### ISSUE TITLE
Kokoro: Build and Device Tests failing due to ... Firebase Test Lab internal bug?!

### ISSUE THREAD

**Issue by vorburger** [google/android-fhir#2488]
[This build](https://source.cloud.google.com/results/invocations/95eed6e4-21f1-4261-91bd-7b52ac5d1e02) for #2487 has [failed](https://github.com/google/android-fhir/files/14623359/android-fhir_Firebase-Test-Lab_bug.txt) e.g. [here](https://firebase.corp.google.com/u/0/project/android-fhir-instrumeted-tests/testlab/histories/bh.96901a7d2453dacf/matrices/7711056212659017752/executions/bs.4c92935b8436b200/logs).

I've no idea what this means, and what could be causing this. 

This looks like it's not (just) a "flaky test" in `android-fhir` anymore (such as e.g. #2485 et al.), but some...  Firebase Test Lab internal bug?!

@jingtang10 @santosh-pingle  how do we proceed here?

**Comment by vorburger** [comment]
It looks like this was some transient issue:

```
(...)

03-16 03:46:03.200: D/statsd(747): StateTracker did not find state value for query key 
03-16 03:46:03.200: W/statsd(747): StateTracker not found for state atom 29
03-16 03:46:03.203: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.apps.gcs/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.203: E/JobScheduler.Concurrency(1327): Error executing JobStatus{f686038 #u0a147/1 com.google.android.apps.gcs/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10147 NET READY}
03-16 03:46:03.203: I/AssistantForeground(3561): (REDACTED) Get launcher package: %s
03-16 03:46:03.203: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.apps.gcs/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.203: E/JobScheduler.Concurrency(1327): Error executing JobStatus{e38ad7a #u0a147/6 com.google.android.apps.gcs/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10147 NET READY}
03-16 03:46:03.203: D/nativeloader(18779): Configuring classloader-namespace for other apk /data/app/~~e-SdM5Jr9TXdAscVa6cE9w==/com.google.android.apps.mtaas.backdrop-QN16GF-2afknqt1rUht5QQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~e-SdM5Jr9TXdAscVa6cE9w==/com.google.android.apps.mtaas.backdrop-QN16GF-2afknqt1rUht5QQ==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.apps.mtaas.backdrop
03-16 03:46:03.204: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.204: E/JobScheduler.Concurrency(1327): Error executing JobStatus{828daad #u0a186/3 com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10186 NET READY}
03-16 03:46:03.204: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.204: E/JobScheduler.Concurrency(1327): Error executing JobStatus{47f0afe #u0a186/9 com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10186 NET CHARGING READY}
03-16 03:46:03.205: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.205: E/JobScheduler.Concurrency(1327): Error executing JobStatus{97f1e57 #u0a186/10 com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10186 NET READY}
03-16 03:46:03.205: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.205: E/JobScheduler.Concurrency(1327): Error executing JobStatus{929bfe6 #u0a186/11 com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10186 NET READY}

(...)

03-16 03:46:03.312: E/JobScheduler.Concurrency(1327): Error executing JobStatus{f686038 #u0a147/1 com.google.android.apps.gcs/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10147 NET READY}
03-16 03:46:03.312: I/DropBoxManagerService(1327): add tag=system_server_wtf isTagEnabled=true flags=0x2
03-16 03:46:03.314: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.apps.gcs/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.314: E/JobScheduler.Concurrency(1327): Error executing JobStatus{e38ad7a #u0a147/6 com.google.android.apps.gcs/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10147 NET READY}
03-16 03:46:03.316: I/GoogleInputMethodService(12731): GoogleInputMethodService.onFinishInput():3227 
03-16 03:46:03.316: I/DropBoxManagerService(1327): add tag=system_server_wtf isTagEnabled=true flags=0x2
03-16 03:46:03.317: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.317: E/JobScheduler.Concurrency(1327): Error executing JobStatus{828daad #u0a186/3 com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10186 NET READY}
03-16 03:46:03.317: I/DropBoxManagerService(1327): add tag=system_server_wtf isTagEnabled=true flags=0x2
03-16 03:46:03.318: I/GoogleInputMethodService(12731): GoogleInputMethodService.updateDeviceLockedStatus():2087 repeatCheckTimes = 0, unlocked = true
03-16 03:46:03.318: I/GoogleInputMethodService(12731): GoogleInputMethodService.onStartInput():1877 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.google.android.apps.mtaas.backdrop fieldId=-1 fieldName=null extras=null}, false)
03-16 03:46:03.318: I/GoogleInputMethodService(12731): GoogleInputMethodService.shouldHideHeaderOnInitialState():4008 ShouldHideHeaderOnInitialState = false
03-16 03:46:03.318: W/InputManager-JNI(1327): Input channel object '866cad2 Splash Screen com.google.android.apps.mtaas.backdrop (client)' was disposed without first being removed with the input manager!
03-16 03:46:03.319: I/GoogleInputMethodService(12731): GoogleInputMethodService.updateDeviceLockedStatus():2087 repeatCheckTimes = 2, unlocked = true
03-16 03:46:03.320: W/WindowManager(1327): Failed looking up window session=Session{1646323 2581:u0a10226} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6050 com.android.server.wm.Session.setOnBackInvokedCallbackInfo:943 android.view.IWindowSession$Stub.onTransact:1180 
03-16 03:46:03.320: E/WindowManager(1327): setOnBackInvokedCallback(): No window state for package:com.android.systemui
03-16 03:46:03.320: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.321: E/JobScheduler.Concurrency(1327): Error executing JobStatus{47f0afe #u0a186/9 com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10186 NET CHARGING READY}
03-16 03:46:03.322: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.322: E/JobScheduler.Concurrency(1327): Error executing JobStatus{97f1e57 #u0a186/10 com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10186 NET READY}
03-16 03:46:03.323: W/ActivityManager(1327): Unable to start service Intent { cmp=com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService } U=0: not found
03-16 03:46:03.323: E/JobScheduler.Concurrency(1327): Error executing JobStatus{929bfe6 #u0a186/11 com.google.android.videos/androidx.work.impl.background.systemjob.SystemJobService u=0 s=10186 NET READY}
03-16 03:46:03.465: W/NotificationHistory(1327): Attempted to add notif for locked/gone/disabled user 0

(...)

03-16 03:46:19.660: W/Binder(1327): Caught a RuntimeException from the binder stub implementation.
03-16 03:46:19.660: W/Binder(1327): java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
03-16 03:46:19.660: W/Binder(1327): 	at android.util.ArraySet.valueAt(ArraySet.java:422)
03-16 03:46:19.660: W/Binder(1327): 	at com.android.server.contentcapture.ContentCapturePerUserService$ContentCaptureServiceRemoteCallback.updateContentCaptureOptions(ContentCapturePerUserService.java:733)
03-16 03:46:19.660: W/Binder(1327): 	at com.android.server.contentcapture.ContentCapturePerUserService$ContentCaptureServiceRemoteCallback.setContentCaptureWhitelist(ContentCapturePerUserService.java:646)
03-16 03:46:19.660: W/Binder(1327): 	at android.service.contentcapture.IContentCaptureServiceCallback$Stub.onTransact(IContentCaptureServiceCallback.java:115)
03-16 03:46:19.660: W/Binder(1327): 	at android.os.Binder.execTransactInternal(Binder.java:1285)
03-16 03:46:19.660: W/Binder(1327): 	at android.os.Binder.execTransact(Binder.java:1244)
03-16 03:46:19.660: W/AiAiAutofill(3513): Failed to set whitelist for augmented autofill service.
03-16 03:46:19.660: W/AiAiAutofill(3513): java.lang.SecurityException: caller is not user's Augmented Autofill Service
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at android.view.autofill.AutofillManager.setAugmentedAutofillWhitelist(AutofillManager.java:2386)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at cgo.b(PG:7)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at cha.g(PG:8)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at cha.i(Unknown Source:3)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at cha.h(PG:2)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at chb.a(PG:2)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at deg.run(PG:47)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at deg.run(PG:73)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at deg.run(PG:71)
03-16 03:46:19.660: W/AiAiAutofill(3513): 	at java.lang.Thread.run(Thread.java:1012)

```
