### ISSUE TITLE
Data Capture Gallery crashes when entering age in "COVID-19 Case Report"

### ISSUE THREAD

**Issue by maanuanubhav999** [google/android-fhir#527]
**Describe the bug**
Data capture gallery crash when trying to input age in "Covid-19 Case Report"

**Component**
SDC gallery app

**To Reproduce**
1. Go to 'COVID-19 Case Report' page in the sdc gallery app'
2. Click on 'Age under Patient Information(section 1)'
3. Enter some value

**Expected behavior**
The app should not crash on data input

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [ Pixel3a emulator]
 - Android version: [11]
 - Build number: [sdk_gphone_x86_arm-userdebug 11 RSR1.201013.001 6903271 dev-keys]
 - Also tested on Realme Narzo, android version 11

**Additional context**
 Cannot compare different data types: Quantity and integer

**Would you like to work on the issue?**
Not sure yet

**Device Logs**
`2021-06-02 03:59:16.879 16134-16134/com.google.android.fhir.datacapture.gallery E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.datacapture.gallery, PID: 16134
    java.lang.IllegalArgumentException: Cannot compare different data types: Quantity and integer
        at com.google.android.fhir.datacapture.validation.MoreTypesKt.compareTo(MoreTypes.kt:26)
        at com.google.android.fhir.datacapture.validation.MinValueConstraintValidator$1.invoke(MinValueConstraintValidator.kt:28)
        at com.google.android.fhir.datacapture.validation.MinValueConstraintValidator$1.invoke(MinValueConstraintValidator.kt:22)
        at com.google.android.fhir.datacapture.validation.ValueConstraintValidator.validate(ValueConstraintValidator.kt:36)
        at com.google.android.fhir.datacapture.validation.QuestionnaireResponseItemValidator.validate(QuestionnaireResponseItemValidator.kt:36)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextViewHolderDelegate$init$$inlined$doAfterTextChanged$1.afterTextChanged(TextView.kt:101)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10703)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13712)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
        at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:228)
        at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
        at android.widget.TextView.doKeyDown(TextView.java:8546)
        at android.widget.TextView.onKeyDown(TextView.java:8320)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2865)
        at android.view.View.dispatchKeyEvent(View.java:14448)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1976)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:555)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1879)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4156)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:451)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6662)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6522)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5951)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6015)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5974)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6160)
2021-06-02 03:59:16.879 16134-16134/com.google.android.fhir.datacapture.gallery E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5982)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6217)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5955)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6015)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5974)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5982)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5955)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8958)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8909)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8860)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5697)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:255)
        at android.app.ActivityThread.main(ActivityThread.java:8192)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)`

**Comment by ekigamba** [comment]
@maanuanubhav999 The cause of the bug is correct. The feature with the bug is https://github.com/google/android-fhir/issues/164 which validates immediately a value is entered. Is it clear how to test the initial feature and probably fix this and other cases that cause the crash?

Does it validate incomplete values? Is it supposed to validate incomplete values?

**Comment by maanuanubhav999** [comment]
@ekigamba thanks, I understood that.

**Comment by maanuanubhav999** [comment]
@ekigamba , yes the feature you have mentioned is working fine as it was supposed to and there is no issue with the questionnaire. Sure I will try to fix this.

**Comment by maanuanubhav999** [comment]
Currently, Only numeric part of the quantity is being handled and as result, when we are validating the inputs we were comparing the QuestionnaireResponseItemAnswerComponent(**Quantity type**) to  **Integer** which was causing the error.
Possible solutions according to me.
1. Change the QuestionnaireResponseItemAnswerComponent(**Quantity type**) to QuestionnaireResponseItemAnswerComponent(**Integer type**) in QuantityViewHolderFactory -->   Temporary Solution
2. Handle other parts of the **Quantity type** as mentioned in [https://www.hl7.org/fhir/datatypes.html#quantity](url)
and then have Validation Improved for checking for Sub-data types of Quantity types.

What should I move forward with, any suggestion? 
@ekigamba @jingtang10

**Comment by ekigamba** [comment]
@maanuanubhav999 That's correct. I think the form authoring might be wrong. The question type is quantity and therefore the min value should also be a quantity. At first, #2 should have been the way to go. However, this would have required declaring the `minValue` as a quantity and this is probably not in the spec https://www.hl7.org/fhir/extension-minvalue.html. The spec supports only **valueDate**, **valueDateTime**, **dateTime**, **valueTime**, **valueDecimal** and **valueInteger**

**Comment by maanuanubhav999** [comment]
Continuing the chat regarding the questionnaire in [https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Questionnaire](url).   @ekigamba The form authoring seems to be correct but using quantity is complex and In chat they recommend using decimal type if the units are fixed But our question has units of three types **days, month, year**.

So should we make changes to the questionnaire??

**Comment by ekigamba** [comment]
@maanuanubhav999 I guess we might have to change the question type and use a fixed value or remove the `minValue` for the timebeing

**Comment by maanuanubhav999** [comment]
@ekigamba okay I will make the changes.

**Comment by maanuanubhav999** [comment]
Hey, @Tarun-Bhardwaj  It is working fine now. I should close the Issue I guess.
