### ISSUE TITLE
SDC Gallery app crashes when trying to load a questionnaire

### ISSUE THREAD

**Issue by deepankarb** [google/android-fhir#587]
**Describe the bug**
SDC Gallery app crashes when trying to load a questionnaire

**Component**
SDC gallery app

**To Reproduce**
1. In Android Studio, run the `datacapturegallery` app
2. App launches, main activity renders
3. Tap on "Real-world lifelines questionnaire"
4. App crashes

**Expected behavior**
Questionnaire to render

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: S
 - Build number: SPP3.210325.010.A1
 - Version: 31

**Additional context**
Stacktrace:
```
2021-06-24 10:15:57.726 31973-31973/com.google.android.fhir.datacapture.gallery E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.datacapture.gallery, PID: 31973
    java.lang.IllegalStateException: Can't access ViewModels from detached fragment
        at androidx.fragment.app.Fragment.getDefaultViewModelProviderFactory(Fragment.java:427)
        at androidx.fragment.app.FragmentViewModelLazyKt$createViewModelLazy$factoryPromise$1.invoke(FragmentViewModelLazy.kt:95)
        at androidx.fragment.app.FragmentViewModelLazyKt$createViewModelLazy$factoryPromise$1.invoke(Unknown Source:0)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:52)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.google.android.fhir.datacapture.QuestionnaireFragment.getViewModel(Unknown Source:2)
        at com.google.android.fhir.datacapture.QuestionnaireFragment.<init>(QuestionnaireFragment.kt:88)
        at com.google.android.fhir.datacapture.gallery.QuestionnaireContainerFragment.onCreateView(QuestionnaireContainerFragment.kt:67)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2952)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7695)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
The issue is the new property created in the fragment https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt#L88 access the view model which isn't allowed.

It really isn't needed. And if the application needs to access the questionnaire itself it should go through the view model rather than using a public function on the fragment.
