### ISSUE TITLE
Data capture gallery app crash on pre-24 emulators

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#642]
**Describe the bug**
Data capture gallery app crashes on pre-24 emulators when navigating to questionnaire

**Component**
SDC gallery app

**To Reproduce**
1. Build and run
2. Go to any questionnaire page

**Stacktrace**

07-09 10:54:09.650 4138-4138/com.google.android.fhir.datacapture.gallery E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.datacapture.gallery, PID: 4138
    java.lang.RuntimeException: An exception happened in constructor of class com.google.android.fhir.datacapture.QuestionnaireViewModel
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:132)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.google.android.fhir.datacapture.QuestionnaireFragment.getViewModel(QuestionnaireFragment.kt)
        at com.google.android.fhir.datacapture.QuestionnaireFragment.access$getViewModel$p(QuestionnaireFragment.kt:34)
        at com.google.android.fhir.datacapture.QuestionnaireFragment$onViewCreated$3.invokeSuspend(QuestionnaireFragment.kt:71)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
        at androidx.lifecycle.DispatchQueue.resume(DispatchQueue.kt:54)
        at androidx.lifecycle.LifecycleController$observer$1.onStateChanged(LifecycleController.kt:40)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:62)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:653)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:2999)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2990)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3124)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3068)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2991)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NoClassDefFoundError: j$.$r8$wrapper$java$util$function$Supplier$-WRP
        at org.apache.commons.lang3.Validate.notNull(Validate.java:224)
        at ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:438)
        at ca.uhn.fhir.parser.ParserState$PreResourceState.enteringNewElement(ParserState.java:994)
    	at ca.uhn.fhir

I have tried disabling coreLibraryDesugaringEnabled... but a different error would show:

     Caused by: java.lang.NoClassDefFoundError: org.apache.commons.lang3.-$$Lambda$Validate$XJJZURDO20sZXXyZMfTRRv13t2c
        at org.apache.commons.lang3.Validate.notNull(Validate.java:224)
        at ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:438)
    	at ca.uhn.fhir.parser.ParserState$PreResourceState.enteringNewElement(ParserState.j

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel4XL emulator
 - Android version: Android 5.0 x86_64

**Additional context**
First reported by @ndegwamartin 

**Would you like to work on the issue?**
NA

**Comment by santosh-pingle** [comment]
I tried above mentioned steps on android api 24, 23 and 21 with Pixel4XL emulator with 86_64 system image, but it was not crashed.
Also selected random questionnaire from the questionnaire list and opened  and submitted the form without crash.

**Comment by jingtang10** [comment]
This problem was resolved in #844
