### ISSUE TITLE
java.lang.NullPointerException: quantity.unit must not be null

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#700]
**Describe the bug**
This crash was seen recently on latest codebase.

java.lang.NullPointerException: quantity.unit must not be null
 at com.google.android.fhir.index.ResourceIndexer.quantityIndex(ResourceIndexer.kt:277)
        at com.google.android.fhir.index.ResourceIndexer.extractIndexValues(ResourceIndexer.kt:99)
        at com.google.android.fhir.index.ResourceIndexer.index(ResourceIndexer.kt:69)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertResource(ResourceDao.kt:202)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll$suspendImpl(ResourceDao.kt:74)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll(Unknown Source:4)
        at com.google.android.fhir.db.impl.DatabaseImpl$insert$2.invokeSuspend(DatabaseImpl.kt:66)
        at com.google.android.fhir.db.impl.DatabaseImpl$insert$2.invoke(Unknown Source:14)
        at androidx.room.RoomDatabaseKt$withTransaction$2.invokeSuspend(RoomDatabase.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)

Resources 
```
{"resourceType":"Observation","id":"633cfdc9-061e-4462-97d3-6f13fa967e6d","code":{"coding":[{"system":"http://loinc.org","code":"8310-5","display":"Temperature"}]},"subject":{"reference":"Patient/2126234"},"valueQuantity":{"value":36.0,"system":"http://unitsofmeasure.org","code":"C"}}


{"resourceType":"Observation","id":"42d0314e-1948-454e-9ef8-5a08041a8d17","code":{"coding":[{"system":"http://loinc.org","code":"8867-4","display":"Heart rate"}]},"subject":{"reference":"Patient/2126234"},"valueQuantity":{"value":76.0,"system":"http://unitsofmeasure.org","code":"/min"}}

{"resourceType":"Observation","id":"5e44c47a-2b52-4b56-8abc-9937eac7ee62","code":{"coding":[{"system":"http://loinc.org","code":"59408-5","display":"Oxygen Saturation"}]},"subject":{"reference":"Patient/2126234"},"valueQuantity":{"value":99.0,"system":"http://unitsofmeasure.org","code":"%"}}

```
https://hl7.org/fhir/R4/bodytemp.html#profile

https://hl7.org/fhir/R4/oxygensat.html

https://hl7.org/fhir/R4/heartrate.html

**Component**
reference app, engine.

**To Reproduce**
Click on Patient on Patient search page -> Click on + (screener encounter) -> take survey -> submit the survey.
While saving extracted resources, crash happens at ResourceIndexer.
It expects unit non null.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@epicadk

**Comment by epicadk** [comment]
Not entirely sure this is because of #682 the error seems to be on line 227 

https://github.com/google/android-fhir/blob/10ddd96d3eddb46ab8aae520298740eea452e232/engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt#L277

Which I haven't modified in #682 , was this working before that pr was merged?

**Comment by santosh-pingle** [comment]
> Not entirely sure this is because of #682 the error seems to be on line 227
> 
> https://github.com/google/android-fhir/blob/10ddd96d3eddb46ab8aae520298740eea452e232/engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt#L277
> 
> Which I haven't modified in #682 , was this working before that pr was merged?

yes, it was able to save resources.(added resources in description are saved resources.)

**Comment by santosh-pingle** [comment]
@epicadk 
After taking latest pull, I see same crash with updated line numbers.

```  java.lang.NullPointerException: quantity.unit must not be null
        at com.google.android.fhir.index.ResourceIndexer.quantityIndex(ResourceIndexer.kt:282)
        at com.google.android.fhir.index.ResourceIndexer.extractIndexValues(ResourceIndexer.kt:100)
        at com.google.android.fhir.index.ResourceIndexer.index(ResourceIndexer.kt:70)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertResource(ResourceDao.kt:202)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll$suspendImpl(ResourceDao.kt:74)
        at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll(Unknown Source:4)

```

**Comment by epicadk** [comment]
> @epicadk
> After taking latest pull, I see same crash with updated line numbers.
> 
> ```
>         at com.google.android.fhir.index.ResourceIndexer.quantityIndex(ResourceIndexer.kt:282)
>         at com.google.android.fhir.index.ResourceIndexer.extractIndexValues(ResourceIndexer.kt:100)
>         at com.google.android.fhir.index.ResourceIndexer.index(ResourceIndexer.kt:70)
>         at com.google.android.fhir.db.impl.dao.ResourceDao.insertResource(ResourceDao.kt:202)
>         at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll$suspendImpl(ResourceDao.kt:74)
>         at com.google.android.fhir.db.impl.dao.ResourceDao.insertAll(Unknown Source:4)
> ```

Ahh yes this makes sense now. I'll look into it should be done by the end of the day.

**Comment by epicadk** [comment]
@Tarun-Bhardwaj this can be marked as done in the FHIR engine library project right?
