### ISSUE TITLE
Patient details card : java.lang.NullPointerException: observationCode must not be null

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#701]
**Describe the bug**
Issue was seen on patient details card.

java.lang.NullPointerException: observationCode must not be null
        at com.google.android.fhir.reference.PatientDetailsViewModel.createConditionItem(PatientDetailsViewModel.kt:119)
        at com.google.android.fhir.reference.PatientDetailsViewModel.getPatientConditions(PatientDetailsViewModel.kt:67)
        at com.google.android.fhir.reference.PatientDetailsViewModel$getPatientConditions$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Component**
reference app

**To Reproduce**
Patient search page -> click on patient -> click on complete survey -> answers the questions -> Submit
App. crash on patient details screen.

 Patient search page -> click on patient (who participated screen encounter survey)-
App. crash on patient details screen.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Working on it to unblock #626

**Comment by santosh-pingle** [comment]
Closing this issue, this issue is not seen anymore, it was already fixed in code repository.
