### ISSUE TITLE
Resource Indexer throws Exception when parsing Observation with Quantity value.

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#768]
**Describe the bug**
FhirPathEngine throws UnsupportedOperationException when evaluating Observation.component.valueQuantity

**Failing Test :**
```
  @Test
  fun index_observation_quantity_type_basic() {

    val observation =
      Observation().apply {
        addComponent().apply {
          this.valueQuantity.apply {
            value = BigDecimal.valueOf(70)
            system = "http://unitsofmeasure.org"
          }
        }
        addComponent().apply {
          this.valueQuantity.apply {
            value = BigDecimal.valueOf(110)
            system = "http://unitsofmeasure.org"
          }
        }
      }

    val resourceIndices = ResourceIndexer.index(observation)
    assertThat(resourceIndices.quantityIndices).isNotEmpty()
  }
```
Observation example on HAPI Server that fails http://hapi.fhir.org/baseR4/Observation/49413

**Exception trace**
```
java.lang.UnsupportedOperationException
	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.getUcumService(HapiWorkerContext.java:289)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.qtyEqual(FHIRPathEngine.java:1670)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.doEquals(FHIRPathEngine.java:1640)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.doContains(FHIRPathEngine.java:2124)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.opUnion(FHIRPathEngine.java:2112)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.operate(FHIRPathEngine.java:1422)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1189)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:525)
	at com.google.android.fhir.index.ResourceIndexerTest.index_observation_quantity_type_basic(ResourceIndexerTest.kt:631)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
```
**Component**
Core library

**Additional context**
Issue was first documented in [#694](https://github.com/google/android-fhir/issues/694#issuecomment-907234781)
Issue is also created for HAPI- [hapifhir-592](https://github.com/hapifhir/org.hl7.fhir.core/issues/592)

**Comment by jingtang10** [comment]
https://github.com/hapifhir/org.hl7.fhir.core/issues/592
