### ISSUE TITLE
Reference app crashed after opening it

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#774]
**Describe the bug**
The reference app throws NPE error on the country value after opening it

**Component**
reference app

**To Reproduce**
1. Open the 'reference app'
2. Crash

**Expected behavior**
It should not crashed

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: [Pixel4 emulator]
 - Android version: [11]
 - Build number: [RSR1.201013.001]

**Additional context**
Error log
```
2021-09-05 19:24:39.484 17706-17706/com.google.android.fhir.reference E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.reference, PID: 17706
    java.lang.NullPointerException: country must not be null
        at com.google.android.fhir.reference.PatientListViewModelKt.toPatientItem(PatientListViewModel.kt:145)
        at com.google.android.fhir.reference.PatientListViewModel.getSearchResults(PatientListViewModel.kt:71)
        at com.google.android.fhir.reference.PatientListViewModel$getSearchResults$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Would you like to work on the issue?**
N.A

**Comment by FikriMilano** [comment]
cc @maanuanubhav999

**Comment by santosh-pingle** [comment]
Working on it.
