### ISSUE TITLE
Reference/Gallery app get crashed when request focus get switched to bottom view.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#863]
**Describe the bug**
Reference/Gallery app get crashed when request focus get switched to bottom view.

**Component**
SDC library, reference app, or SDC gallery app

**To Reproduce**
1. Open reference app
2. Click on patient record, it opens patient details screen
3. Click on edit icon, it opens patient edit screen.
4. Click on city edittext box
5. Click on next request focus on soft keyboard.
6. Application get crashed.

Gallery App : 
1. Open Gallery App.
2. Click on Neonate record.
3. Click on city edittext box
4. Click on next request focus on soft keyboard.
5. app get crashed when focus reach at bottom view.

_**Need to debug the issue further to fix the issue.**_

logs : 
2021-10-25 17:56:42.629 30171-30171/com.google.android.fhir.reference E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.reference, PID: 30171
    java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
        at android.widget.TextView.onKeyUp(TextView.java:8618)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2866)
        at android.view.View.dispatchKeyEvent(View.java:14247)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:476)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1861)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4085)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5955)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5823)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5318)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5375)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5493)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5349)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5550)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5322)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5375)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5349)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5322)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8095)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8046)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8006)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5083)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2021-10-25 17:56:42.630 30171-30171/com.google.android.fhir.reference E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Basically, this issue is reproducible when inputEdittext box which is hidden behind the soft keyboard at the time when focus is transferred to it.
