### ISSUE TITLE
Validation with display only question item crashing as it has no answer

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#913]
**Describe the Issue**

Validation with display only question item crashing as it has no answer         
QuestionnaireResponseValidator -> line -> validate(questionnaireItem.item, questionnaireResponseItem.answer[0].item, context)

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.google.android.fhir.datacapture.validation.QuestionnaireResponseValidator.validate(QuestionnaireResponseValidator.kt:56)
        at com.google.android.fhir.datacapture.validation.QuestionnaireResponseValidator.validate(QuestionnaireResponseValidator.kt:56)
        at com.google.android.fhir.datacapture.validation.QuestionnaireResponseValidator.validate(QuestionnaireResponseValidator.kt:56)
```

**Would you like to work on the issue?**

**Comment by santosh-pingle** [comment]
@maimoonak 
Is it still reproducible?

**Comment by maimoonak** [comment]
I have confirmed that validation is now working with enablement and display. Looks like it has been resolved.

**Comment by f-odhiambo** [comment]
CC @Tarun-Bhardwaj and @jingtang10

**Comment by Tarun-Bhardwaj** [comment]
Closing it as per the last comment from @maimoonak
